version: "2.1"

services:
  ui:
    extends:
      file: .user.compose.yml
      service: base_config

    build: 
      context: containers/ui

    working_dir: /home/node/ui
    volumes:
      - ./ui:/home/node/ui
    command: ng serve --host=0.0.0.0
    privileged: true
    ports:
      - 4200:4200

  api:
    extends:
      file: .user.compose.yml
      service: base_config
    build:
      context: ./containers/api

    volumes:
      - ./:/go/src/github.com/smileinnovation/imannotate

    working_dir: /go/src/github.com/smileinnovation/imannotate
    environment:
      BIN_APP_PORT: 8000
    ports:
      - 3000:3000
    privileged: true

